apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: pv-nfs-grafana
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/persistent/grafana
    server: 10.1.10.15
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pv-claim
spec:
  storageClassName: pv-nfs-grafana
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
